apiVersion: v1
kind: Template
metadata:
  annotations:
    description: Microsweeper Template
    iconClass: icon-java
    tags: microservice,thorntail
  name: microsweeper
objects:

## Image Stream
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: microsweeper
    name: microsweeper
  spec:
    tags:
    - name: latest

## Build
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      build: microsweeper
    name: microsweeper
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'microsweeper:latest'
    runPolicy: Serial
    source:
      git:
        uri: ${GIT_URI}
        ref: ${GIT_REF}
      type: Git
    strategy:
      sourceStrategy:
        env:
          - name: MAVEN_MIRROR_URL
            value: ${MAVEN_MIRROR_URL}
        from:
          kind: ImageStreamTag
          name: 'redhat-openjdk18-openshift:1.3'
          namespace: openshift
      type: Source

## Build Pipeline
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: microsweeper-build
  spec:
    runPolicy: SerialLatestOnly
    source:
      git:
        ref: ${GIT_REF}
        uri: ${GIT_URI}
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline

## Deployment Config
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: microsweeper
    labels:
      app: microsweeper
  spec:
    replicas: 1
    selector:
      app: microsweeper
      deploymentconfig: microsweeper
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: microsweeper
          deploymentconfig: microsweeper
        name: microsweeper
      spec:
        containers:
        - env:
          - name: ENVIRONMENT
            value: "${ENVIRONMENT}"
          - name: GC_MAX_METASPACE_SIZE
            value: "500"
          image: microsweeper
          imagePullPolicy: Always
          name: microsweeper
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 75
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - microsweeper
        from:
          kind: ImageStreamTag
          name: microsweeper:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: microsweeper
    name: microsweeper
  spec:
    ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: http
    selector:
      deploymentconfig: microsweeper
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: microsweeper
    name: microsweeper
  spec:
    to:
      kind: Service
      name: microsweeper
      weight: 100
parameters:
- displayName: Git URI
  description: URL to Git source
  name: GIT_URI
  required: true
  value: https://github.com/bbenz/microsweeper-demo.git
- displayName: Git Ref
  description: Git reference branch/tag
  name: GIT_REF
  required: true
  value: solution
- displayName: Environment
  description: Environment (DEVELOPMENT, STAGING, PRODUCTION)
  name: ENVIRONMENT
  required: true
  value: DEVELOPMENT
- displayName: Maven Mirror URL
  description: Maven Mirror URL
  name: MAVEN_MIRROR_URL
  required: false
